import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Remove attributes injected by browser extensions
              document.documentElement.removeAttribute('data-darkreader-mode');
              document.documentElement.removeAttribute('data-darkreader-scheme');
              document.documentElement.removeAttribute('data-darkreader-proxy-injected');

              // Ensure consistent rendering for dynamic content
              if (!document.documentElement.hasAttribute('data-rendered-on-server')) {
                document.documentElement.setAttribute('data-rendered-on-server', 'true');
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
